spring.datasource.url=jdbc:mysql://localhost:3306/government_scheme
spring.datasource.username=root
spring.datasource.password=Tejas@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
